### PR TITLE
Brackets in ontology names

### LINKED ISSUE #306: Brackets in ontology names result in improper Neo4j file names
When names in the underlying ontology contain brackets, the generated files for the Neo4j import are not proper.

Example:
- Name in the Snomed CT ontology: `Patient (person)`
- When writing the files for the Neo4j import, BioCypher transforms this name to CamelCase (results in: `Patient (person)`).
- The generated import statement `bin/neo4j-admin import --database=neo4j --delimiter="\t" --array-delimiter="|" --quote="'" --force=true --skip-bad-relationships=true --skip-duplicate-nodes=true --nodes="/biocypher-out/20240115145536/Patient (person)-header.csv,/biocypher-out/20240115145536/Patient (person)-part.*"` fails with `java.lang.IllegalArgumentException`. [Neo4j can not handle whitespaces in filenames](https://neo4j.com/developer/kb/space-in-import-filename-for-load-csv/).

After removing the whitespace and the brackets from the file names and the import statement everything works as expected.

Is there any advice on how to handle this?
I would suggest to check for not supported characters (such as brackets) and remove them before writing the files (probably in  [name_sentence_to_pascal](https://github.com/biocypher/biocypher/blob/main/biocypher/_translate.py#L470) or somewhere in [write](https://github.com/biocypher/biocypher/blob/main/biocypher/_write.py) .

### PR DESCRIPTION
**Pull request by nilskre**
Fixes #306 

Added a function for checking if a string is compliant with the Neo4j naming rules. When writing the node and edge files it is checked, whether the file name is compliant with the Neo4j naming rules. If not the file name is adapted accordingly by removing the characters in question.

### CODE REVIEW

**Comment by nilskre** [comment]
> Should we replace dots with underscores categorically?

From my point of view, there is nothing that speaks against it. 
To get it right: Would this mean to 
1) adapt the source code for the implicit inheritance to already produce compliant names e.g. `KEGG_pathway`
2) or would this mean to replace the dot with an underscore in the `parse_label` method?

**Comment by slobentanzer** [comment]
Good question. I think since this is also a Neo4j-specific problem, for now the less deleterious way would be to change it at the latest possible moment, which is the parsing.

Something to keep in mind: if we do that, we need to update the docs again to explain and replace the dots in the examples.

**Comment by nilskre** [comment]
Sounds good. I would propose to create an issue for this and implement it in a separate PR (then code and docs can be changed at the same time). Otherwise we first need to get the changes from the other branch.

**Comment by slobentanzer** [comment]
OK, I'll merge this one after the current merge has completed. You can go ahead and do the separate issue / PR.

**Review by slobentanzer — APPROVED** [review]

**Pull request merged**
