### PR TITLE
fix(import_call):Database name after import prefix

### PR DESCRIPTION
**Pull request by mbaric758**
Refs: #363

### CODE REVIEW

**Review by nilskre — CHANGES_REQUESTED** [review]
Hi @mbaric758  ,
thanks for investigating and providing this Pull Request!
This leaked, that our current unit test suite lacks the behavior of checking the correct functioning of the import script.
To avoid this in the future: Can you add unit tests for checking this?
Thanks in advance.

**Comment by mbaric758** [comment]
Hi @nilskre I added a test to check whether the import call works, however I think there might be a problem with the `bin/` prefix which is added by default to the import call by the `_get_default_import_call_bin_prefix` function in `_neo4j.py`. The way I usually interact with Neo4j is by adding the path of `neo4j-admin` to `PATH` and `PYTHONPATH` so it's a global variable and the import call works without changing directories to the location of Neo4j installation. 

In case of having to change directories to the Neo4j path before calling the import call, I think this would create problems since pytest has to be called from the biocypher root directory. I didn't change the addition of the `bin/` prefix to the import call in the current PR, so maybe you should also run the test on your system to see if the test works?

**Comment by slobentanzer** [comment]
Hi @mbaric758,
the bin prefix derives from the way that Neo4j handles its folder structure. If you execute a script in the root of a Neo4j DBMS, the neo4j-admin binary is in the bin directory. This is important for the use case of multiple DBMSs on one system. You cannot just put all of them on the path.

Regarding the unit tests: these should not be dependent on the operating system whatsoever. Ideally, we would write tests that test only the validity of the import call, without having to execute it. It is up to us to come up with a method to do this (can be regex or anything else that lets you compare / validate a string). :)

**Comment by mbaric758** [comment]
Thanks @slobentanzer for explaining this ! I understood from the previous comment that the test should run the import call itself to check its functionality, but in that case the `test_construct_import_call` in `test_neo4j.py` should be sufficient for checking the import call structure since only the database name location has changed.

**Comment by slobentanzer** [comment]
I think @nilskre's remark was pointing out that we are not currently considering the bug that you found, i.e. the order of arguments. Maybe we should just add a check for the order then?

**Comment by mbaric758** [comment]
In that case, I modified the existing `test_construct_import_call`, to also check that the database name is now located after the `import` command.

**Comment by slobentanzer** [comment]
@nilskre something's up with the MacOS runners, they seem to fail arbitrarily. Is this related to #342?

**Comment by nilskre** [comment]
> @nilskre something's up with the MacOS runners, they seem to fail arbitrarily. Is this related to #342?

Yes, that is the related issue. I tried one week ago to fix this, by setting the CICD to macos-latest again. The current state is documented there.

Current state summary:
- macos-latest = macos-14 at the moment
- We have set the CICD to use macos-13 to fix the Python setup issue we encountered (until the maintainers have fixed the Python setup action (is now fixed for macos-latest).
- Unfortunately the Docker installation action is not working with macos-14 due to incompatible Apple hardware (see linked documentation in #342). The Docker installation action will only be updated for the future macos-15.
=> Thus I have not found a fast and easy fix for this at the moment.

**Comment by slobentanzer** [comment]
> Thus I have not found a fast and easy fix for this at the moment.

I am not sure I fully get what goes wrong, but it failing arbitrarily is a nuisance. Would it be a solution to remove the Neo4j/Docker stuff from the MacOS runners so they at least run quickly? We could argue that we test the online Neo4j functionality on Linux, and only return it to MacOS if they fix the Apple support / Docker workflow.

**Comment by nilskre** [comment]
Yes, that would be an option 👍

**Comment by mbaric758** [comment]
Hi @nilskre , is there an update on the status of the PR, or are we still waiting for the MacOS testing issue to be resolved ?

**Comment by nilskre** [comment]
Hi @mbaric758 ,
sorry for any inconvenience while waiting for this PR to be resolved.
At the moment I am on vacation and will be back in Biocypher development probably later this year.
To get this done and merged: You could implement the proposed fix to remove the Neo4j Docker tests for Macos from the CICD pipeline (should be sufficient to comment the line where Docker is installed for Macos ( https://github.com/biocypher/biocypher/blob/3de6eca31a29734a7473fdbcae41c71bb3aba678/.github/actions/test/action.yaml#L14).
Thanks in advance!
And then it should be easy for @slobentanzer to quickly review and merge.

**Comment by slobentanzer** [comment]
Hi @mbaric758,
sorry for the delay, as Nils explained, he is currently off and I was busy with submitting the latest paper. I fixed the CI configuration and will review the PR soon.

**Review by slobentanzer — APPROVED** [review]
Looks good, many thanks @mbaric758 :)

Bumping patch version

**Pull request merged**
